version: "3.8"

services:
  bot:
    container_name: telegram-bot
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/home/telegram-bot
    restart: always
    env_file:
      - .env
