version: "3.8"

services:

  bot:
    container_name: telegram-bot
    build: .
    stdin_open: true
    tty: true
    environment:
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - .:/home/telegram-bot
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:11.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
