version: "3.8"

services:
  bot:
    container_name: telegram-bot
    build: .
    stdin_open: true
    tty: true
    environment:
      RUBYOPT: -W:no-deprecated -W:no-experimental
    volumes:
      - .:/home/telegram-bot
    restart: always
